### ISSUE TITLE
Code completion improvements

### ISSUE THREAD

**Issue by dbshell** [dbshell/dbgate#26]
- Show only, when letter is typed (not after "," , enter ...)
- Add table names to offered items
- (NTH: parse common table epxressions)

**Comment by dbshell** [comment]
fixed

**Comment by Noxis73** [comment]
I just stumpled upon that "fix" today, because I was confused why the code suggestion always only works for the first column :)
Any chance to bring this feature back? 
Why? I always write the comma at the beginning of my select-columns, because in this way i can delete the whole line without struggling with wrong commas.

For example:

Select 

person
, birthday
, city
, number
, etc.

Thanks for considering! 

P.s. Fantastic tool for Sql development!

**Comment by Noxis73** [comment]
@janproch probably you didn't noticed my comment so far, because the issue is closed... would you mind to review it? thanks!
